#include QMK_KEYBOARD_H
#include "keymap_slovenian.h"

// Left-hand home row mods
#define GUI_A LGUI_T(SI_A)
#define ALT_S LALT_T(SI_S)
#define SFT_D LSFT_T(SI_D)
#define CTL_F LCTL_T(SI_F)

// Right-hand home row mods
#define CTL_J RCTL_T(SI_J)
#define SFT_K RSFT_T(SI_K)
#define ALT_L LALT_T(SI_L)
#define GUI_CCAR RGUI_T(SI_CCAR)

// Layers
#define _QWERTY 0
#define _LOWER 1
#define _RAISE 2
#define _ADJUST 3

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ,-----------------------------------------.                    ,-----------------------------------------.
 * | QUOT |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   | DEL  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                    |  Y   |  U   |  I   |  O   |  P   |  Š   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | LSFT |  A   |  S   |  D   |  F   |  G   |                    |  H   |  J   |  K   |  L   |  Č   |  Ž   |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * | LCTL |  Z   |  X   |  C   |  V   |  B   |  ESC  |    |  BSPC |  N   |  M   | COMM | DOT  | MINS |  Đ   |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   | LGUI | LALT | RASE | / SPC   /      \ ENT   \  | LWR  | RALT | RGUI |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
 [_QWERTY] = LAYOUT(
  SI_QUOT,  SI_1,   SI_2,    SI_3,    SI_4,    SI_5,                    SI_6,    SI_7,    SI_8,    SI_9,    SI_0,     KC_DEL,
  KC_TAB,   SI_Q,   SI_W,    SI_E,    SI_R,    SI_T,                    SI_Z,    SI_U,    SI_I,    SI_O,    SI_P,     SI_SCAR,
  KC_LSFT,  GUI_A,  ALT_S,   SFT_D,   CTL_F,   SI_G,                    SI_H,    CTL_J,   SFT_K,   ALT_L,   GUI_CCAR, SI_ZCAR,
  KC_LCTL,  SI_Y,   SI_X,    SI_C,    SI_V,    SI_B, KC_ESC,   KC_BSPC, SI_N,    SI_M,    SI_COMM, SI_DOT,  SI_MINS,  SI_DSTR,
                           KC_LGUI, KC_LALT, MO(_RAISE), KC_SPC, KC_ENT, MO(_LOWER), KC_RALT, KC_RGUI
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | ESC  | EXLM |  AT  | HASH | DLR  | PERC |                    | LEFT | DOWN |  UP  | RGHT |      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |      |      |      |      |      |       |    |       |      | UNDS | LCBR | RCBR | PLUS | PIPE |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |      | /       /      \       \  |MO(3) |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_RAISE] = LAYOUT(
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                    KC_F7,   KC_F8,   KC_F9,   KC_F10,   KC_F11,  KC_F12,
  _______, _______, _______, _______, _______, _______,                  _______, _______, _______, _______,  _______, _______,
  KC_ESC,  SI_EXLM, SI_AT,   SI_HASH, SI_DLR,  SI_PERC,                  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT,  XXXXXXX, XXXXXXX,
  _______, _______, _______, _______, _______, _______, _______,_______, XXXXXXX, SI_UNDS, SI_LCBR, SI_RBRC,  SI_PLUS, SI_PIPE,
                             _______, _______, _______, _______, _______,  MO(_ADJUST), _______, _______
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | GRV  |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    | CIRC | AMPR | ASTR | LPRN | RPRN | TILD |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |  F7  |  F8  |  F9  | F10  | F11  | F12  |       |    |       | PLUS | MINS | EQL  | LBRC | RBRC | BSLS |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |MO(3) | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_LOWER] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                     _______, _______, _______, _______, _______, _______,
  KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                       KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD,
  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   _______, _______,  SI_PLUS, SI_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
                             _______, _______, MO(_ADJUST),  _______, _______,  _______, _______, _______
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |RM_TOG|RM_HUE|RM_SAT|RM_VAL|      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |RM_NEX|RM_HUE|RM_SAT|RM_VAL|      |      |       |    |       |      |      |      |      |      |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |      | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
  [_ADJUST] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  RM_TOGG, RM_HUEU, RM_SATU, RM_VALU, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  RM_NEXT, RM_HUED, RM_SATD, RM_VALD, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                             _______, _______, _______, _______, _______,  _______, _______, _______
  )
};

// clang-format on
